--- 
- name: Instaldor de paquetes YUM
  hosts: localhost 
  become: True 
  tasks: 
    - name: Instalar última versión de Apache 
      yum: 
        name: httpd
        state: latest
    - name: Actualizar todos los paquetes 
      yum:
        name: '*'
        state: latest
    - name: Instalar grupo 
      yum: 
        name: "@Development tools"
        state: present
    